name: Sign Docker image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "Published Docker image that needs to be signed"
        required: true
        type: string
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: mkomatinovic/charts
          path: charts
          ref: INTERNAL-master # TODO: change to default branch

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # get from workflow_call
          password: ${{ secrets.DOCKERHUB_TOKEN }} # get from workflow_call

      - name: cosign-installer
        uses: sigstore/cosign-installer@v2.4.0
        
      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: "true"
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{  }} #steps.build-and-push.outputs.digest